apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
# 사용하려는 환경 설정 값을 넣어준다.
data:
  TIME_ZONE: Asia/Seoul
  my.cnf: |
    [mysqld]
    max_connections = 1000
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci