apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-label
  template:
    metadata:
      labels:
        app: student-label
    spec:
      containers:
      - name: student
        image: jjjwww8802/student-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_PASSWORD
